# Generated by Django 3.0.8 on 2022-03-15 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'board',
            },
        ),
        migrations.CreateModel(
            name='DOSEL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=32)),
                ('contact', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'DOSEL',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=100)),
                ('b_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Board')),
            ],
            options={
                'db_table': 'subject',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=32)),
                ('contact', models.CharField(max_length=100)),
                ('user_type', models.IntegerField()),
                ('b_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Board')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=100)),
                ('b_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Board')),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Subject')),
            ],
            options={
                'db_table': 'topic',
            },
        ),
        migrations.CreateModel(
            name='MCQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('option_1', models.CharField(max_length=100)),
                ('option_2', models.CharField(max_length=100)),
                ('option_3', models.CharField(max_length=100)),
                ('option_4', models.CharField(max_length=100)),
                ('correct_ans', models.CharField(max_length=100)),
                ('explanation', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
                ('b_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Board')),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Subject')),
                ('t_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Topic')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Users')),
            ],
            options={
                'db_table': 'mcq',
            },
        ),
        migrations.CreateModel(
            name='BoardUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=32)),
                ('contact', models.CharField(max_length=100)),
                ('b_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Board')),
            ],
            options={
                'db_table': 'boardusers',
            },
        ),
    ]
