# Generated by Django 3.0.8 on 2022-03-16 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardusers',
            name='name',
        ),
    ]
