# Generated by Django 2.2.1 on 2022-03-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_boardusers_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_type',
            field=models.CharField(max_length=100),
        ),
    ]
